version: '3.5'

networks:
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=4w'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    restart: always
    expose:
      - 9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:6.7.0
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
